<?php
/**
 * @autogenerated
 * @copyright Copyright (c) 2020 Scandiweb, Ltd (https://scandiweb.com)
 */

use \Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(
    ComponentRegistrar::THEME,
    'frontend/Scandiweb/pwa',
    __DIR__
);
